---
title: Webjeda cards
timezone: UTC


collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  colleges:
    title: colleges
    output: true


email: contact@iosd.tech
description: 'Event Portal for IOSD'
title: Events


baseurl: "/iosd-events"
url: http://iosd.tech



default-image: webjeda-logo-big.jpg

built-by: dhruv
copyright:
  name: dhruv
  link: http://dhruvramdev.me


markdown: kramdown

permalink: "/:title/"
paginate: 9
paginate_path: "/page:num/"


analytics: UA-83979019-1

disqus-shortname: webjeda-demo

facebook: http://facebook.com/webjeda

quora: http://quora.com/sharathdt

twitter: http://twitter.com/@webjeda

github: http://github.com/webjeda

fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda
sass:
  style: compressed


# Ruby Gems
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-admin